version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build/
    overwrite: yes
 
permissions:
  - object: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    
hooks:
  AfterInstall:
    - location: scripts/server-stop.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/server-start.sh
      timeout: 60
      runas: root
