server:
  port: 8081

spring:
  profiles:
    default: dev
---
# Develop server
server:
  port: 8082

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/promptDB?serverTimezone=Asia/Seoul # 127.0.0.1
    username: root
    password: oracle

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

#  sql:
#    init:
#      schema-locations:
#        - classpath:db/migration/v2_sql_ddl.sql
#      data-locations:
#        - classpath:db/seed/v4_sql_seed_ddl.sql
#      encoding: UTF-8
#      mode: always

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace